config/routes.rb
Rails.application.routes.draw do
  get 'datasets/new_upload', to: 'datasets#new_upload'
  get 'terms/recrawl', to: 'terms#recrawl'
  get 'datasets/recrawl_collection', to: 'datasets#recrawl_collection'
  post 'datasets/recrawl_items', to: 'datasets#recrawl_items'
  post 'relay_results', to: 'dataitems#save_results'
  post 'update_status', to: 'dataitems#save_status_message'
  
  resources :datasets
  resources :terms
  resources :dataitems

  root 'datasets#index'

  get 'datasources', to: 'datasets#sources'

end

app/models/dataset.rb
class Dataset
  include Mongoid::Document
  include Mongoid::Paperclip
  include GlobalID::Identification
  
  # Fields
  field :name
  field :input_query_fields, type: Hash
  field :source
  field :collection_tag
  has_mongoid_attached_file :selector_file
  field :recrawl_frequency
  field :recrawl_interval
  field :pbox_messages
  
  # Associations
  has_many :terms
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  include CollectData
  include SaveData
  include IndexData
  include DeleteSelectors
  include UpdateColselec
  include SaveColselec
  include DatasetsHelper
  include ScheduleRecrawl
  include CrawlerManager
  def index
    @datasets = Dataset.all
  end

  def destroy
    @dataset = Dataset.find(params[:id])

    # Delete associated terms and items
    Resque.enqueue(DeleteSelectors, @dataset.terms)

    # Destroy and show notification
    respond_to do |format|
      if @dataset.destroy
        format.html { redirect_to action: "index", notice: 'Collection was successfully deleted' }
      end
    end
  end

  # Recrawl mutiple terms in dataset
  def recrawl_collection
    @dataset = Dataset.find(params[:collection])
  end

  # Recrawl list of items
  def recrawl_items
    # Get list of selectors and dataset from params
    recrawl_list = params["selectors_to_recrawl"].map{|s| Term.find(s)}
    @dataset = Dataset.find(params["collection"])

    # Save info needed to rescrape datast
    check_if_schedule_changed(@dataset, recrawl_list, params["recrawl_frequency"], params["recrawl_interval"])

    # Recrawl and redirect
    CollectData.perform(@dataset.source, @dataset, recrawl_list) if params["recrawl_interval"] != "never"
    redirect_to @dataset
  end

  def sources
    @datasets = Dataset.all
    @crawlers = JSON.parse(list_crawlers)
    @crawler_names = @crawlers.map{|c| c["classname"]}
  end

  def edit
    @dataset = Dataset.find(params[:id])
    @crawler = JSON.parse(get_crawler_info(@dataset.source))
    @input = @crawler["input_params"]
  end

  def update
    @dataset = Dataset.find(params[:id])

    # Update recrawl schedule
    check_if_schedule_changed(@dataset, @dataset.terms, params["recrawl_frequency"], params["recrawl_interval"])

    # Update the selectors
    find_updated_selectors(dataset_params)
    update_selectors(params["recrawl_frequency"], params["recrawl_interval"])
    @dataset.update_attributes(dataset_params)
 
    # Collect data and save selectors
    if params.include?("commit")
      CollectData.perform(dataset_params["source"], @dataset, @all_modified_selectors)
    end
    
    respond_to do |format|
      if @dataset.update_attributes(dataset_params)
        format.html { redirect_to @dataset, notice: 'Dataset was successfully updated.' }
      else
        format.html { render :new }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # New function for things on the upload form
  def new_upload
    new
  end

  def new
    @crawler = JSON.parse(get_crawler_info(params["source"]))
    @input = @crawler["input_params"]
    @dataset = Dataset.new
  end

  def create
    # Save the dataset
    save_dataset(dataset_params)
    
    # Save the recrawl info
    save_rescrape_info(@dataset, @dataset.terms, params["recrawl_frequency"], params["recrawl_interval"])
         
    # Just show selectors saved
    if params.include?("save")
      save_success
      
    # Collect data and save selectors
    elsif params.include?("commit")
      collect_data(dataset_params)
    end
  end

  # Put all items for dataset in JSON
  def show
    set_dataset
  end

  private
  
  # Also collect data
  def collect_data(dataset_params)
    CollectData.perform(dataset_params["source"], @dataset, @dataset.terms)
    save_success
  end

  # Show it successfully saved
  def save_success
    respond_to do |format|
      if @dataset.save
        format.html { redirect_to @dataset, notice: 'Dataset was successfully saved.' }
        format.json { render @dataset, status: :created, location: @dataset }
      else
        format.html { render :new }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_dataset
    @dataset = Dataset.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dataset_params
    params[:input_query_fields] = {empty: "empty"} if params[:input_query_fields].empty?
    name = params.require(:dataset).permit(:name)
    return name.merge(params.permit(:source)).merge({input_query_fields: params.require(:input_query_fields)}.to_hash).merge(params.permit(:pbox_messages))
  end
end

app/helpers/datasets_helper.rb
module DatasetsHelper
  include ApiCalls
  
  # Get count of all results
  def get_overall_count
    return get_total_docs(ENV["PROJECT_INDEX"])
  end

  # Get number of results for single dataset
  def get_count_per_dataset(dataset)
    return get_collection_count(dataset.collection_tag, ENV["PROJECT_INDEX"])
  end

  # Generate JSON with all data to print on show view
  def gen_print_data(dataset)
    result_data = dataset.dataitems.inject([]) do |all_items, item|
      all_items.push(Dataitem.find(item).as_json)
    end
    result_data
  end

  # Generate a label for the checkbox
  def gen_checkbox_label(selector)
    label = ""
    selector.term_query.each do |query, value|
      label += value.to_s+" "
    end

    label += " (Last Collected:"+selector.latest_collection_time.to_s+")"
    return label
  end

  # Generate default value for recrawl frequency
  def gen_recrawl_freq_val
    if @dataset.recrawl_frequency
      return @dataset.recrawl_frequency
    else
      return "1"
    end
  end

  # See if the button should be checked for recrawl interval
  def check_recrawl_interval?(interval)
    # Check current val
    if @dataset.recrawl_interval == interval
      return true

    # Default to once if no val
    elsif !@dataset.recrawl_interval && interval == 'once'
      return true
    else
      return false
    end
  end
end

app/views/datasets/_edit_form.html.erb
<%= form_for(@dataset) do |f| %>
<div class="app-sidebars">
  <div class="app-sidebars-small">
    <h2>Details</h2>
    <p>Selected Sources</p>
    <ul class="list-items">
      <li><i class="<%= @crawler["icon"] %>"></i> <%= @crawler["name"] %></li>
    </ul>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <hr>
    <a class="button warning button-full" href="<%= datasets_path %>" class="button">Cancel & Start Again</a>
  </div>

  <div class="app-sidebars-large">
    <h2>Enter Selectors</h2>
    <p>Single selectors or multiple are allowed and will be crawled as single queries</p>
    <ol class="unstyled" id="term-input-list">
      <% @dataset.input_query_fields.each do |in_f| %>
      <li>
         <%= render 'edit_query_fields', count: in_f[0], in_f: in_f[1] %>
      </li>
      <% end %>
    </ol>
    <%= hidden_field_tag 'source', @dataset.source %>
    <%= render 'recrawl_frequency_form' %>
    <a id="add-another-query" class="button info">+ Add Another Term</a>
    <button class="button pull-center" type="submit" name="save"><i class="icon-checkmark"></i> Save Selectors</button>
    <button class="button pull-right" type="submit" name="commit"><i class="icon-checkmark"></i> Start Collecting</button>
  </div>
</div>
<% end %>

<script type="text/template" id="template-add-term-input">
<li>
  <hr>
  <%= render 'query_fields', count: "template" %>
</li>
</script>

app/views/datasets/_edit_query_fields.html.erb
<% @input.each do |field| %>
  <%= label_tag field[0].to_sym %>
  <% if field[1] == "string" %>
    <%= text_field_tag "input_query_fields[#{count}][#{field[0]}]", in_f[field[0]] %>
  <% elsif field[1] == "file" %>
    <%= text_field_tag "input_query_fields[#{count}][#{field[0]}]", in_f[field[0]] %>
  <% end %>
<% end %>

app/views/datasets/_form.html.erb
<%= form_for(@dataset) do |f| %>
<div class="app-sidebars">
  <div class="app-sidebars-small">
    <h2>Details</h2>
    <p>Selected Sources</p>
    <ul class="list-items">
      <li><i class="<%= @crawler["icon"] %>"></i> <%= @crawler["name"] %></li>
    </ul>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <hr>
    <a class="button warning button-full" href="<%= datasets_path %>" class="button">Cancel & Start Again</a>
  </div>

  <div class="app-sidebars-large">
    <h2>Enter Selectors</h2>
    <p>Single selectors or multiple are allowed. To upload a JSON with
    selectors instead of entering them manually, <%= link_to "use the upload
    form", datasets_new_upload_path(source: params[:source]) %>.</p>
    <ol class="unstyled" id="term-input-list">
      <li>
        <%= render 'query_fields', count: 0 %>
      </li>
    </ol>
    <%= hidden_field_tag 'source', params[:source] %>
    <%= render 'recrawl_frequency_form' %>
    <a id="add-another-query" class="button info">+ Add Another Term</a>
    <button class="button pull-center" type="submit" name="save"><i class="icon-checkmark"></i> Save Selectors</button>
    <button class="button pull-right" type="submit" name="commit"><i class="icon-checkmark"></i> Start Collecting</button>
  </div>
</div>
<% end %>

<script type="text/template" id="template-add-term-input">
<li>
  <hr>
  <%= render 'query_fields', count: "template" %>
</li>
</script>

app/views/datasets/_new_upload_form.html.erb
<%= form_for @dataset, html: {multipart: true}  do |f| %>
<div class="app-sidebars">
  <div class="app-sidebars-small">
    <h2>Details</h2>
    <p>Selected Sources</p>
    <ul class="list-items">
      <li><i class="<%= @crawler["icon"] %>"></i> <%= @crawler["name"] %></li>
    </ul>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <hr>
    <a class="button warning button-full" href="<%= datasets_path %>" class="button">Cancel & Start Again</a>
  </div>

  <div class="app-sidebars-large">
    <h2>Upload Selector List</h2>
    <p>Upload a JSON list of selectors. The keys should be the names of the
    fields for the data source as specified in CrawlerManager. If you aren't
    adding selectors from a pre-existing list in bulk, <%= link_to "the normal
    selector input form", new_dataset_path(source: params[:source]) %> is a better option.</p>
    <ol class="unstyled" id="term-input-list">
      <li>
	<%= f.label :selector_file %>
        <%= f.file_field :selector_file %>
      </li>
    </ol>
    <%= hidden_field_tag 'source', params[:source] %>
    <%= hidden_field_tag 'input_query_fields' %>
    <button class="button pull-right" type="submit" name="commit"><i class="icon-checkmark"></i> Start Collecting</button>
    <button class="button pull-right" type="submit" name="save"><i class="icon-checkmark"></i> Save Selectors</button>
  </div>
</div>
<% end %>

<script type="text/template" id="template-add-term-input">
<li>
  <hr>
  <%= render 'query_fields', count: "template" %>
</li>
</script>

app/views/datasets/_progress_box.html.erb
<style media="screen" type="text/css">

  .progressbox {
  border: 1px solid black;
  height: 200px;
  padding: 10px 10px 10px 10px;
  overflow: scroll;
  }

</style>


<div class="progressbox" id=<%="pbox_"+@dataset.id.to_s%>>
  <%= raw(show_message(@dataset.pbox_messages)) %>
</div>

<br />

app/views/datasets/_query_fields.html.erb
<% @input.each do |field| %>
  <%= label_tag field[0].to_sym %>
  <% if field[1] == "string" %>
    <%= text_field_tag "input_query_fields[#{count}][#{field[0]}]" %>
  <% elsif field[1] == "file" %>
    <%= text_field_tag "input_query_fields[#{count}][#{field[0]}]" %>
  <% end %>
<% end %>

app/views/datasets/_recrawl_form.html.erb
<%= form_tag datasets_recrawl_items_path do |f| %>
  <%= check_box_tag('check_all') %><br />
  <% @dataset.terms.each do |selector| %>
    <%= check_box_tag 'selectors_to_recrawl[]', selector.id, false, class: 'selector_checkbox' %>
    <%= label_tag gen_checkbox_label(selector) %>
    <br />
    <% end %>
    <hr>

    <%= render 'recrawl_frequency_form' %>
    
    <%= hidden_field_tag 'collection', @dataset.id %><br /><br />
    <%= submit_tag "Re-Crawl" %>
    
<% end %>

app/views/datasets/_recrawl_frequency_form.html.erb
Enter the frequency with which these selectors should be crawled.<br />
<%= number_field_tag 'recrawl_frequency', gen_recrawl_freq_val %><%= label_tag "times per: "%>

<%= radio_button_tag 'recrawl_interval', 'never', check_recrawl_interval?('never') %><%= label_tag "never" %>
<%= radio_button_tag 'recrawl_interval', 'once', check_recrawl_interval?('once') %><%= label_tag "only now" %>
<%= radio_button_tag 'recrawl_interval', 'minute', check_recrawl_interval?('minute') %><%= label_tag "minute" %>
<%= radio_button_tag 'recrawl_interval', 'hour', check_recrawl_interval?('hour') %><%= label_tag "hour" %>
<%= radio_button_tag 'recrawl_interval', 'day', check_recrawl_interval?('day') %><%= label_tag "day" %>
<%= radio_button_tag 'recrawl_interval', 'week', check_recrawl_interval?('week') %><%= label_tag "week" %>
<%= radio_button_tag 'recrawl_interval', 'month', check_recrawl_interval?('month') %><%= label_tag "month" %>
<%= radio_button_tag 'recrawl_interval', 'year', check_recrawl_interval?('year') %><%= label_tag "year" %>
			    

app/views/datasets/edit.html.erb
<div class="wrapper">

  <div class="app-title">
    <h1><span>Step 2</span> Edit Collector Selectors</h1>
  </div>

  <%= render 'edit_form' %>

</div>

app/views/datasets/index.html.erb
<div class="wrapper">
  <div class="app-title">
    <h1><%= get_overall_count %> Results Harvested</h1>
  </div>

  <div class="grid-two">
    <div class="one-column">
      <a class="button primary button-full" href="/datasources"><i class="icon-plus"></i> Add New Collection</a>
    </div>
    <div class="one-column">
      <a class="button primary button-full" href="http://0.0.0.0:3001"><i class="icon-logo"></i> View in LookingGlass</a>
    </div>
  </div>

  <div class="app-content">
  <% @datasets.each do |dataset| %>
    <div class="grid-three">
      <div class="two-column">
        <h2><% if dataset.name != "" %><%= dataset.name %><% else %><span>(No Title)</span><% end %></h2>
        <% if get_count_per_dataset(dataset) > 0 %><%= get_count_per_dataset(dataset) %><% else %>No<% end %> items collected
      </div>
      <div class="one-column text-right">
        <a class="button info" href="/datasets/<%= dataset.id %>">View
          Collection</a>  <br /><br />
	<%= link_to raw("<i class='icon-trash'></i> Delete"), dataset,
	                            method: :delete, class: "remove danger
          pull-right button" %>
      </div>
    </div>
    <hr>
  <% end %>
  </div>

</div>

app/views/datasets/new.html.erb
<div class="wrapper">

  <div class="app-title">
    <h1><span>Step 2</span> Collector Selectors</h1>
  </div>

  <%= render 'form' %>

</div>

app/views/datasets/new_upload.html.erb
<div class="wrapper">

  <div class="app-title">
    <h1><span>Step 2</span> Collector Selectors</h1>
  </div>

  <%= render 'new_upload_form' %>

</div>

app/views/datasets/show.html.erb
<div class="wrapper">
  <div class="app-title">
    <h1><span>Collection:</span> <%= @dataset.name %></h1>
    <%= link_to raw("<i class='icon-trash'></i> Delete"), @dataset,
		        method: :delete, class: "remove danger pull-right button" %>
    <a href="/datasets/<%= @dataset.id%>/edit"><i class="icon-modified"></i>
      Edit</a>
    <%= link_to raw("<i class='icon-query'></i> Re-Crawl"),
      datasets_recrawl_collection_path({collection: @dataset}), class: "view info pull-right button" %>
  </div>

  <div class="app-content">
    <div class="grid-three">
      <div class="two-column">
        <h2><% if get_count_per_dataset(@dataset) > 0 %><%= get_count_per_dataset(@dataset) %><% else %>No<% end %> Items
          Collected</h2>
	<h4><%="Collection will be recrawled
	"+pluralize(@dataset.recrawl_frequency, 'time')+" per
	"+@dataset.recrawl_interval %></h4>
      </div>
      <div class="one-column text-right">
	
      <% @crawlers.each do |crawler| %>
        <% if crawler["classname"] == @dataset.source %>
        <i class="<%= crawler["icon"] %>"></i> <%= crawler["name"] %>
        <% end %>
      <% end %>
      </div>
    </div>

    <%= render 'progress_box' %>

    <% if @dataset.input_query_fields %>
    <h3>Selectors</h3>
    <ul class="list-items">
      
      <% @dataset.terms.each do |query_fields| %>
      <li>
	<i class="icon-terms"></i>
        <% query_fields.term_query.each do |query, value| %>
          <%= value %>
        <% end %>
	  <%= query_fields.latest_collection_time %>

	<%= link_to raw("<i class='icon-trash'></i> Delete"), query_fields,
	    method: :delete, class: "remove danger pull-right" %>
	<%= link_to raw("<i class='icon-query'></i> Re-Crawl"),
	    terms_recrawl_path({selector: query_fields}), class: "view info pull-right" %>
      </li>
    <% end %>
    </ul>
    <% else %>
    <h3>Hmm</h3>
    <p>No search terms were specified in this collection.</p>
    <% end %>
    <hr>

  </div>
</div>

app/views/datasets/sources.html.erb
<%= form_tag('/datasets/new', method: 'get') do %>
<div class="wrapper">
  <div class="app-title">
    <h1><span>Step 1</span> Select a collection source</h1>
  </div>
  <div class="app-grid-items">
    <% @crawlers.each do |crawler| %>
    <div class="app-grid-item">
       <h1><i class="<%= crawler["icon"] %>"></i> <%= crawler["name"] %></h1>
       <p><%= crawler["description"] %></p>
       <button name="source" value="<%= crawler["classname"] %>">+ Add Source</button>
    </div>
    <%end %>
    <div href="javascript:void(0)" class="app-grid-item-not">
      <div>
        <h2>More Sources</h2>
        <h2>Coming Soon</h2>
        <p>Request a new service</p>
      </div>
    </div>
  </div>
</div>
<% end %>